In [8]:
! pip install torch torchvision torchaudio transformers datasets numpy pandas

In [9]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
from datasets import load_dataset
import pandas as pd
import numpy as np

In [10]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

In [13]:
data = load_dataset('quocanh34/mental_health_dataset_1')

Found cached dataset parquet (/home/terminator/.cache/huggingface/datasets/quocanh34___parquet/quocanh34--mental_health_dataset_1-a7427549bb4961d1/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7)


  0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
data_dict = data['train']

In [48]:
def sentiment_score(text: str) -> int:
    tokens = tokenizer.encode(text, return_tensors='pt')
    result = model(tokens)
    print(result.logits)
    return int(torch.argmax(result.logits) + 1)

print(sentiment_score("You are so ugly that, when One Direction saw you they went other direction"))
print(sentiment_score("I am feeling lonely"))
print(sentiment_score("It's been while I haven't met her"))
print(sentiment_score("I scored good marks in Maths"))
print(sentiment_score("Smile on the face of orphan children makes me feel happy"))

tensor([[ 2.3499,  1.4388,  0.1122, -1.5969, -1.9020]],
       grad_fn=<AddmmBackward0>)
1
tensor([[ 0.3881,  0.5972,  0.4350, -0.5397, -0.7959]],
       grad_fn=<AddmmBackward0>)
2
tensor([[-0.3334,  0.0947,  0.4711,  0.0139, -0.2089]],
       grad_fn=<AddmmBackward0>)
3
tensor([[-1.8378, -1.3210,  0.5200,  1.4175,  1.0245]],
       grad_fn=<AddmmBackward0>)
4
tensor([[-2.3668, -2.2021, -0.1391,  1.7753,  2.0968]],
       grad_fn=<AddmmBackward0>)
5


# Score varies between 1 to 5
- 1 => More Negative
- 2 => Negative
- 3 => Neutral
- 4 => Positive
- 5 => More Positive 